package Chapter8;

public class Ex8_14 {
	public static void main(String[] args) {

		try { 
			 method1();
		} catch (Exception e) {
			System.out.println("main에서 예외가 처리됨");
		     e.printStackTrace();
		}
	}
	static void method1() throws Exception {
		throw new Exception();
		
	}
}